[package]
org = "nipunal"
name = "hello_world_service"
version = "0.1.0"
distribution = "2201.12.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="metrics.logs"
version = "@toml.version@"
repository="local"
